services:
  airfront:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LAND_URL: https://${DOMAIN}
    image: ${DOCKER_IMAGE}
    container_name: airfront
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_INTERNAL_URL=http://airbff:8080
      - LAND_URL=https://${DOMAIN}
    networks:
      - app_internal
      - air_shared
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app_internal:
    external: true
  air_shared:
    external: true


