services:
  Marusia:
    build:
      context: .
      dockerfile: Dockerfile
    image: marusia-prod_img
    container_name: Marusia
    ports:
      - "8080:80"   # HTTP
      - "443:443"   # HTTPS для React-приложения
      - "8081:8081" # Landing
      - "8082:8082" # Demo
      - "8083:8083" # Widget
      - "8084:8084" # Pay
      - "8085:8085" # Insta
      - "8086:8086" # WHATS
      - "8087:8087" # TGUSER
      - "8088:8088" # TGBOT
      - "8090:8090" # Analytics
    volumes:
      - ./build:/var/www/html:rw
      - marusia_data:/data
      - marusia_logs:/var/log/Marusia
      - marusia_mysql_data:/var/lib/mysql
      - marusia_mysql_logs:/var/log/mysql
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    environment:
      - HOST=info-bot.online  # Указываем реальный хост
      - NGINX_PORT=443  # Порт для HTTPS

volumes:
  marusia_data:
  marusia_logs:
  marusia_mysql_data:
  marusia_mysql_logs:
