services:
  Marusia:
    image: marusia-prod_img
    container_name: Marusia
    ports:
      - "8080:80"   # HTTP
      - "443:443"   # HTTPS для React-приложения
      - "8081:8081" # Landing
      - "8082:8082" # Demo
      - "8083:8083" # Widget
      - "8084:8084" # Pay
      - "8085:8085" # Instagram
      - "8086:8086" # WHATS
      - "8087:8087" # TGUSER
      - "8088:8088" # TGBOT
      - "8090:8090" # Analytics
    volumes:
      - /run/mysqld:/run/mysqld
      - ./host.pem:/etc/ssl/custom/host.pem:ro
      - ./host-key.pem:/etc/ssl/custom/host-key.pem:ro
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - ./build:/var/www/html:rw
      - marusia_react_files:/var/www/html:rw
      - ./build:/bot/Marusia/build:ro
      - marusia_data:/data
      - marusia_logs:/var/log/Marusia
#      - marusia_mysql_data:/var/lib/mysql
#      - marusia_mysql_logs:/var/log/mysql
      # volume для s3 файлов
      - /var/www/s3:/var/www/s3:rw
      - /var/www/landing:/var/www/landing:ro
#    restart: unless-stopped
    restart: always # Перезапускать контейнер при сбоях и при запуске Docker
    #sysctls:
    #  - net.ipv6.conf.all.disable_ipv6=1
    #  - net.ipv6.conf.default.disable_ipv6=1
    environment:
      # ВАЖНО: Укажите здесь доменное имя вашего сервера
      - HOST=info-bot.online
      - NGINX_PORT=443  # Порт для HTTPS
#    network_mode: "host"
volumes:
  marusia_data:
  marusia_logs:
#  marusia_mysql_data:
#  marusia_mysql_logs:
  marusia_react_files:
